# Generated by Django 4.0.3 on 2022-03-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='comment_post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='comment_user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='post_author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='post_categories',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='time_pub',
            new_name='post_time_pub',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='category_thru',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post',
            new_name='post_thru',
        ),
        migrations.AlterField(
            model_name='author',
            name='author_rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=128),
        ),
    ]
