# Generated by Django 4.0.3 on 2022-05-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_comment_post_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
