# Generated by Django 4.0.3 on 2022-06-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_authorsubscribers_author_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
