# Generated by Django 4.0.3 on 2022-07-21 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0008_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='categorysubscribers',
            options={'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'post category', 'verbose_name_plural': 'post categories'},
        ),
        migrations.AddField(
            model_name='author',
            name='user_en_us',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='имя пользователя'),
        ),
        migrations.AddField(
            model_name='author',
            name='user_ru',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='имя пользователя'),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_name_en_us',
            field=models.CharField(help_text='category', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_name_ru',
            field=models.CharField(help_text='category', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_en_us',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='comm_post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='comm_post'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_en_us',
            field=models.TextField(default='', null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_ru',
            field=models.TextField(default='', null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.SmallIntegerField(default=0, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='имя пользователя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(help_text='category', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, through='news.CategorySubscribers', to=settings.AUTH_USER_MODEL, verbose_name='subscribers'),
        ),
        migrations.AlterField(
            model_name='categorysubscribers',
            name='category_thru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='categorysubscribers',
            name='subscriber_thru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='subscriber'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='comm_post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.SmallIntegerField(default=0, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time_pub'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='news.author', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='', verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cats',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='isUpdated',
            field=models.BooleanField(default=False, verbose_name='edited'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.SmallIntegerField(default=0, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time_pub'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('AR', 'article'), ('NW', 'news')], default='NW', max_length=2, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='cat_thru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='corr_category'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='post_thru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='corr_post'),
        ),
    ]
