# Generated by Django 4.0.3 on 2022-07-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_author_rating_alter_author_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_en_us',
            new_name='user_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_name_en_us',
            new_name='cat_name_en',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body_en_us',
            new_name='body_en',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_en_us',
            new_name='post_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body_en_us',
            new_name='body_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_en_us',
            new_name='title_en',
        ),
    ]
