# Generated by Django 4.0.3 on 2022-07-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_rename_user_en_us_author_user_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user_en',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user_ru',
        ),
    ]
